/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: e8170b34083285713b2a0a756487502a)
interface __BaseEnv_CloudflareEnv {
	DATABASE_REGISTRY: KVNamespace;
	AI: Ai;
	ASSETS: Fetcher;
	GENERATION_MODEL: "@cf/meta/llama-3.3-70b-instruct-fp8-fast";
	RAG_API: Fetcher /* cracha-worker-rag */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GENERATION_MODEL">> {}
}
