/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 3480ec125b67a7a51b345dd88b7bb440)
interface __BaseEnv_CloudflareEnv {
	DATABASE_REGISTRY: KVNamespace;
	AI: Ai;
	ASSETS: Fetcher;
	GENERATION_MODEL: "deepseek/deepseek-v4.1-flash";
	GENERATION_REASONING: "low";
	STRIPE_PRICE_CREDITS_S: "price_1U45HmKErihln31nI18CKkEz";
	STRIPE_PRICE_CREDITS_M: "price_1U45HsKErihln31n71w9wdKG";
	STRIPE_PRICE_CREDITS_L: "price_1U45HwKErihln31n00NaCUAU";
	NEXT_PUBLIC_SUPABASE_URL: string;
	NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: string;
	NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
	RAG_API: Fetcher /* cracha-worker-rag */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./custom-worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GENERATION_MODEL" | "GENERATION_REASONING" | "STRIPE_PRICE_CREDITS_S" | "STRIPE_PRICE_CREDITS_M" | "STRIPE_PRICE_CREDITS_L" | "NEXT_PUBLIC_SUPABASE_URL" | "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY" | "NEXT_PUBLIC_SUPABASE_ANON_KEY">> {}
}
